version: 2.1

orbs:
  rn: react-native-community/react-native@7.1.0
  windows: circleci/windows@2.4.0
  android: circleci/android@2.0.3
  macos: circleci/macos@2.2.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  verify:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install node modules for package
          command: cd package && npm install
      - run:
          name: Install node modules for example app
          command: cd example && npm install
      - run:
          name: Lint JS Code (ESLint)
          command: cd package && npx eslint src
      - run:
          name: Lint Example app JS code (ESLint)
          command: cd example && npx eslint .

  test:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install node modules for package
          command: cd package && npm install
      - run:
          name: Run unit tests with Jest
          command: cd package && npx jest src

  build_example_windows:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install examples
          command: cd package; npm install; cd ../example; npm install
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\example\windows\example.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\example\windows\example.sln
      - run:
          name: Build example Windows
          command: cd example; npx react-native run-windows --no-packager --no-launch --arch x64 --logging --no-deploy

  build_example_ios:
    executor: rn/macos
    steps:
      - checkout
      - run:
          name: Install deps
          command: cd package && npm install && cd ../example && npm install
      - run:
          name: Install Pods
          command: cd example && npx pod-install
      - run:
          name: Build the iOS example project
          command: cd example/ios && export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -workspace example.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11' -scheme example -parallelizeTargets -configuration Debug -derivedDataPath build  -UseModernBuildSystem=YES

  android-debug:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    working_directory: ./example/android
    steps:
      - checkout:
          path: ~/project
      - run:
          command: npm install
      - run:
          name: Assemble debug build
          command: |
            ./gradlew clean build

  ios-debug:
    macos:
      xcode: 13.3.1
    working_directory: /Users/distiller/project
    steps:
      - checkout:
          path: ~/project
      - run:
          command: cd package && npm install
      - run:
          command: cd example && npm install
      - run:
          command: cd example/ios && pod install
      - run:
          name: Compile iOS app
          command: |
            cd ios && xcodebuild -workspace example.xcworkspace -configuration Debug -scheme example CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_BITCODE=NO

workflows:
  slider-full-ci:
    jobs:
      - checkout_code
      - verify:
          requires:
            - checkout_code
      - test:
          requires:
            - verify
      - build_example_windows:
          requires:
            - verify
      - android-debug:
          requires:
            - verify
      - ios-debug:
          requires:
            - verify
